steps:
- name: 'teracy/angular-cli'  
  args: ['npm', 'install']
- name: 'teracy/angular-cli'  
  args: ['ng', 'build', '--prod']
  env:
    - 'NODE_OPTIONS=--max_old_space_size=8048'
- name: 'okumaonome/firebase-tools'  
  args: ['firebase', 'deploy', '--project', 'memphis-eats', '--only', 'hosting:memphis-eats-staging', '--token', '$_FIREBASE_TOKEN']
timeout: "2000s"